[package]
name = "tiber-process-linux"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
rustix = { workspace = true, features = ["process"] }
tiber-process-service = { path = "../tiber-process-service" }

[dev-dependencies]
tempfile.workspace = true
tiber-process-core = { path = "../tiber-process-core" }
tiber-workflow-core = { path = "../tiber-workflow-core" }

[lints]
workspace = true

[[bin]]
name = "tiber-process-launcher"
path = "src/bin/tiber-process-launcher.rs"
